# Site settings
title: "I'd like a website…"
description: > # this means to ignore newlines until "baseurl:"
  A set of (hopefully thought-provoking) questions to ask yourself when you
  get that “I want a website” feeling.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: mozz100
github_username:  mozz100
homepage: http://www.rmorrison.net

# Build settings
safe: true